### ISSUE TITLE
Archive pages (categories for posts) look a bit strange -> should be more or less like product categories 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#102]
Ability to write a text that explains under + custom image 
<img width="1353" alt="Skärmavbild 2021-07-29 kl  13 32 19" src="https://user-images.githubusercontent.com/48952732/127484921-264d88d0-1ee6-4c3c-8a03-e2cdb3902452.png">

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done

**Comment by ZlatanBajric** [comment]
<img width="1350" alt="Skärmavbild 2021-07-30 kl  10 41 23" src="https://user-images.githubusercontent.com/48952732/127626654-a9b7207a-e094-45dd-995d-88fd53c8f379.png">
White gap?

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done
