### ISSUE TITLE
When selecting a sub category -> Breadcrumbs dont change + url stays the same 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#104]
<img width="865" alt="Skärmavbild 2021-07-29 kl  14 01 57" src="https://user-images.githubusercontent.com/48952732/127488332-fbf27509-ac2b-4b06-a20d-2b278f302993.png">

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done
