### ISSUE TITLE
Wrong spelling on meta tags (brand name) 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#109]
Says "heaven" instead of "Haven" 
<img width="377" alt="Skärmavbild 2021-07-29 kl  14 46 43" src="https://user-images.githubusercontent.com/48952732/127494372-80fc6c57-0b7d-400d-a3cc-93682e5bd94f.png">

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done
