### ISSUE TITLE
Articles/Posts dont look like in the editor (missing formating) 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#110]
https://www.prephaven.se/inlagg/fjallvandring-vad-ska-jag-packa 
<img width="846" alt="Skärmavbild 2021-07-29 kl  14 53 21" src="https://user-images.githubusercontent.com/48952732/127495585-4488f4bc-7b35-49bf-b595-a53e31afbbda.png">
<img width="997" alt="Skärmavbild 2021-07-29 kl  14 53 18" src="https://user-images.githubusercontent.com/48952732/127495587-7e64e523-9991-49ad-bb8c-f59c8892ef1c.png">

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done
