### ISSUE TITLE
Ask UI team to create relevant icons 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#112]
<img width="1314" alt="Skärmavbild 2021-07-30 kl  10 43 15" src="https://user-images.githubusercontent.com/48952732/127626934-0308760b-e034-4084-b431-20fd9c3c2844.png">
<img width="1281" alt="Skärmavbild 2021-07-30 kl  10 43 12" src="https://user-images.githubusercontent.com/48952732/127626940-d1aaffe2-4ced-439b-89ae-112f1bc7074d.png">

**Comment by ZlatanBajric** [comment]
The Swe - ENG say more or less the same thing

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done
