### ISSUE TITLE
Increase the width limit of the H1 on the slider 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#113]
<img width="1326" alt="Skärmavbild 2021-07-30 kl  10 45 17" src="https://user-images.githubusercontent.com/48952732/127627124-4da335ab-5b44-4d81-bc6a-e591a9ec0885.png">

**Comment by ZlatanBajric** [comment]
Make sure it looks good on mobile too -> If not a good idea then make the H1 smaller so that it does not push the secondary text too low

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done
