### ISSUE TITLE
Where does the user edit the "gift" Icon + image on home 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#124]
<img width="1205" alt="Skärmavbild 2021-08-31 kl  12 26 06" src="https://user-images.githubusercontent.com/48952732/131486759-ed77d891-ef07-49ef-8dd6-36a4694a26e4.png">

**Comment by MelikaH-seeba** [comment]
done @ZlatanBajric

**Comment by ZlatanBajric** [comment]
I cant find it @MelikaH-seeba  :)

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric  pages -> home page -> scroll down to Voucher section -> first field called **voucher icon**

**Comment by ZlatanBajric** [comment]
1. Lets not call it voucher (as the client wants to use it for something else) -> section # ? 
2. I see the icon but not where to change the image in that section?

**Comment by MelikaH-seeba** [comment]
1. **special** is the new name
2.  image is the last field in section special
