### ISSUE TITLE
Breadcrumbs not following the url/heading 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#125]
<img width="457" alt="Skärmavbild 2021-08-31 kl  12 29 59" src="https://user-images.githubusercontent.com/48952732/131487277-4fa0c425-d79f-42e0-9e28-cb661db33589.png">

Says "GSA" -> Should say the same thing as the heading

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric  done
