### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by belmahadzimusic** [seeba-se/Prep-Haven#42]
- [x] When switching languages, it always brings you on homepage rather than keeping you on the page you are on
- [x] On Certified Foods page, at the end of the text it says: "Translated with..."

**Comment by MelikaH-seeba** [comment]
@belmahadzimusic 
we have agreed on this approach (to the homepage) since we did not have enough time to implement that kind of automatic translation. I do not think it is wrong, it is just an another approach.

**Comment by belmahadzimusic** [comment]
@MelikaH-seeba deal then, I will close this issue now :)
