### ISSUE TITLE
Single product page

### ISSUE THREAD

**Issue by belmahadzimusic** [seeba-se/Prep-Haven#46]
- [x] On mobile, Add to cart button and button for choosing amount of products are not looking right.
- [x] "Easy-to-transport" text is gray and it should be green.
- [x] On desktop, layout of "What you can find in..." things is weird and depends a lot on how many words there is. Can we make this flexible somehow?

**Comment by MelikaH-seeba** [comment]
@belmahadzimusic can you explain "weird" xD

**Comment by belmahadzimusic** [comment]
@MelikaH-seeba haha it probably got moved around when you put real content in, so now layout is not in some sort of grid like it is on the design
