### ISSUE TITLE
Several sections do not show content when being updated

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#48]
<img width="881" alt="Skärmavbild 2021-07-04 kl  12 22 32" src="https://user-images.githubusercontent.com/48952732/124381393-99fa0e80-dcc2-11eb-9eed-3cd55c48c0ee.png">

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric i have tested the rest of the custom fields and they are updating as they should, just this voucher part updates a little bit slower... not sure why.
