### ISSUE TITLE
Wrong lang in WP.. 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#53]
<img width="1196" alt="Skärmavbild 2021-07-11 kl  12 08 56" src="https://user-images.githubusercontent.com/48952732/125191052-c7096c80-e240-11eb-84cf-55e1766d2599.png">

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric could not reproduce this case, can you tell me where is it?
