### ISSUE TITLE
Where do we edit the footer? 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#55]
<img width="1349" alt="Skärmavbild 2021-07-11 kl  12 34 49" src="https://user-images.githubusercontent.com/48952732/125191771-654b0180-e244-11eb-920d-b1db899e0e7e.png">

**Comment by MelikaH-seeba** [comment]
Pages > Home page > scroll to the bottom, there is a section Footer.
If you want to edit the menus, go to Appearance > Menus and select one of four menus for footer (Shop/Butik, Info/Information). These menus have Footer1 or Footer2 name next to them. For Shop/Butik I left the section of code that calls in two latest products to show above the links selected in backend menus.
@ZlatanBajric

**Comment by ZlatanBajric** [comment]
Where do we edit the "About GSA" ?

**Comment by MelikaH-seeba** [comment]
pages -> Home page -> scroll to the bottom, there is a section footer :) @ZlatanBajric
