### ISSUE TITLE
New pages are not published when created (Example: Terms & Conditions) 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#56]
https://www.prephaven.se/terms-conditions

**Comment by MelikaH-seeba** [comment]
because we have to make them in our nextjs application too and collect it from wordpress...this is not a standard wordpress app. prephaven.se shows only nextjs application @ZlatanBajric

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done

**Comment by ZlatanBajric** [comment]
Remove too? :)

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric yes :)
