### ISSUE TITLE
Stange behaviour (Images) 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#58]
Depending on if you 1. refresh or 2.press the logo -> when going back to home, different images are shown. 

https://user-images.githubusercontent.com/48952732/125192572-d5f41d00-e248-11eb-8b8e-59c8e7f7dfa6.mov

**Comment by ZlatanBajric** [comment]
So this is resolved? :)

**Comment by MelikaH-seeba** [comment]
> So this is resolved? :)

I believe so :) @ZlatanBajric
