### ISSUE TITLE
Where does the user edit the header?

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#59]
<img width="1363" alt="Skärmavbild 2021-07-11 kl  13 07 18" src="https://user-images.githubusercontent.com/48952732/125192724-9c6fe180-e249-11eb-8053-1ded134051ce.png">

1. The text 
2. The primary menu
3. The secondary menu (top menu)

**Comment by MelikaH-seeba** [comment]
1. Pages > Home page > scroll down to the Navbar (first accordion in Home page section)
2. & 3. Appearance > Menus 
<img width="1083" alt="Screenshot 2021-07-16 at 15 37 56" src="https://user-images.githubusercontent.com/57252386/125956758-da915fbf-4964-4c64-8e9a-37a0a23c3b32.png">

Navbar desktop menus are primary menus and Top menus are secondary menus

**Comment by ZlatanBajric** [comment]
<img width="398" alt="Skärmavbild 2021-07-28 kl  11 02 28" src="https://user-images.githubusercontent.com/48952732/127295254-acd8fd1c-e408-4dac-ad30-248d19885be9.png">
And this?

**Comment by MelikaH-seeba** [comment]
> 1. Pages > Home page > scroll down to the Navbar (first accordion in Home page section)

@ZlatanBajric

**Comment by MelikaH-seeba** [comment]
just make sure you are on the right language page @ZlatanBajric

**Comment by ZlatanBajric** [comment]
#GettingOld
