### ISSUE TITLE
Remove/turn of the megamenu 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#65]
After some consideration, we will most likely turn off the megamenu. It behaves strangely atm and not to waste more time on it, we will turn it off for now and maybe revisit it sometime in the future. 
<img width="1354" alt="Skärmavbild 2021-07-16 kl  12 15 16" src="https://user-images.githubusercontent.com/48952732/125932787-21633618-6bce-4cb4-95fd-0e16cc81896e.png">

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done
