### ISSUE TITLE
Replace "payment logos" with official klarna branding 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#71]
<img width="345" alt="Skärmavbild 2021-07-28 kl  11 22 08" src="https://user-images.githubusercontent.com/48952732/127298049-3d6e4016-3455-4fa7-9ce7-6cdfbbf75d7b.png">
https://developers.klarna.com/resources/branding/#2-payment-method-display

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric is there any other link, it seems like this one is not available anymore

**Comment by ZlatanBajric** [comment]
https://docs.klarna.com/marketing/se/

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric  is this what you mean? 
<img width="1440" alt="Screenshot 2021-09-09 at 09 16 52" src="https://user-images.githubusercontent.com/57252386/132640493-246acc66-214d-48c6-ad3d-0267befecfaa.png">

**Comment by ZlatanBajric** [comment]
I would go with something like this: https://www.klarna.com/demo/se/sv-SE/kco/checkout (footer payment logos) 
or like we have on Molimenti but with the new klarna logo. 

Also, we can remove the text "vi accepterar"

**Comment by MelikaH-seeba** [comment]
<img width="1440" alt="Screenshot 2021-09-09 at 11 59 15" src="https://user-images.githubusercontent.com/57252386/132665648-bb903836-0b61-4702-b253-2bf30a0a16df.png">
we have those logos on our klarna iframe already. But in footer we can only add this pink klarna badge and add it to our other payment logos, molimenti used the old downloadable image, but now they do not offer this solution as you can see here https://docs.klarna.com/marketing/se/get-started/logos-trademarks/
@ZlatanBajric

**Comment by ZlatanBajric** [comment]
Then lets stick to the pinkie one and just remove the text above? :)

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done
