### ISSUE TITLE
I removed product categories that are not relevant... and this happened 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#74]
<img width="1225" alt="Skärmavbild 2021-07-28 kl  11 42 22" src="https://user-images.githubusercontent.com/48952732/127301028-4d5e76d0-fa80-4c8b-9287-6b84bdb4b1fc.png">

**Comment by MelikaH-seeba** [comment]
probably because you refreshed the page. You need to wait for changes to show on a webpage and then prephaven.se -> click our products link...until we solve this bug @ZlatanBajric
