### ISSUE TITLE
"product section label" -> Ability to edit the content (what to show) -> Category or product 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#77]
<img width="1263" alt="Skärmavbild 2021-07-28 kl  12 38 06" src="https://user-images.githubusercontent.com/48952732/127308850-1f8c37ec-4784-4410-9b5d-65ed44250702.png">
<img width="843" alt="Skärmavbild 2021-07-28 kl  12 38 19" src="https://user-images.githubusercontent.com/48952732/127308882-484de518-1a1e-42c6-bcc2-83ea2f58199c.png">

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric this will display 2 last added products with the category "featured" / "utvalda" (featured for english version, utvalda for swedish)
