### ISSUE TITLE
Currency symbol (Swedish) is always behind the amount 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#82]
<img width="135" alt="Skärmavbild 2021-07-28 kl  13 26 08" src="https://user-images.githubusercontent.com/48952732/127314795-bdd9fb2a-c07e-4fe7-bb76-8f792543aafb.png">

3396 KR 

(Also no no commas and no decimals)

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done
