### ISSUE TITLE
Cart translation - Varukorg 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#83]
<img width="277" alt="Skärmavbild 2021-07-28 kl  13 31 02" src="https://user-images.githubusercontent.com/48952732/127315360-e769fd69-576d-4a33-b474-2d1d61be9c6d.png">

Cart -> Varukorg

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done

**Comment by ZlatanBajric** [comment]
<img width="308" alt="Skärmavbild 2021-07-29 kl  09 48 46" src="https://user-images.githubusercontent.com/48952732/127452854-3f7c8e49-a4ff-46df-a38e-6aa1ea909b63.png">
@MelikaH-seeba

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric can you please add one product for english site so I can test it on both?

**Comment by ZlatanBajric** [comment]
Added two

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done
