### ISSUE TITLE
Where do we edit social media links 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#85]
<img width="264" alt="Skärmavbild 2021-07-28 kl  13 33 37" src="https://user-images.githubusercontent.com/48952732/127315666-8daf95c2-229e-4015-9f07-432de8f9c9bd.png">

**Comment by MelikaH-seeba** [comment]
Pages -> home page or hem page -> scroll to the bottom and find Footer
<img width="967" alt="Screenshot 2021-07-29 at 09 39 59" src="https://user-images.githubusercontent.com/57252386/127451669-f5d517df-4668-4e1a-b778-3de27cb7feab.png">
