### ISSUE TITLE
Translation of hyperlink on homepage 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#86]
<img width="1084" alt="Skärmavbild 2021-07-28 kl  13 39 30" src="https://user-images.githubusercontent.com/48952732/127316344-915c900b-3729-4738-939e-cdbd511e3ed5.png">

"Learn more" -> "Läs mer"

**Comment by MelikaH-seeba** [comment]
pages -> Home page (sv)-> Navigate to accordion named Badges -> find fields "badge 1 link", "badge 2 link" and "badge 3 link" -> edit

<img width="1007" alt="Screenshot 2021-07-28 at 16 22 07" src="https://user-images.githubusercontent.com/57252386/127339181-158589c8-51f1-499a-b379-6e529e830329.png">
