### ISSUE TITLE
Translation of cart pop-up 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#87]
<img width="507" alt="Skärmavbild 2021-07-28 kl  13 43 53" src="https://user-images.githubusercontent.com/48952732/127316781-37f1cdb7-60fd-4e2f-84b0-fb732bf87cf3.png">

Buttons: 
"Cart" -> "Visa" 
"Continue shopping" -> "Fortsätt handla"

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done

**Comment by ZlatanBajric** [comment]
Correction -> "Visa" -> "Till Kassan"

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done
