### ISSUE TITLE
Blogg -> "All posts" does not actually show all the posts. 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#90]
https://user-images.githubusercontent.com/48952732/127453581-3595aec4-3ee6-4526-be96-063f55ffdf48.mov

Also, "all posts" should be first.

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric there was a misunderstanding with design team, it is fixed now

**Comment by ZlatanBajric** [comment]
Pagination? And after how many?

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric currently no pagination. What is your suggestion?

**Comment by ZlatanBajric** [comment]
Is it lazy loading or something? What if there are 40 posts? Are they just listed or?

**Comment by MelikaH-seeba** [comment]
https://user-images.githubusercontent.com/57252386/128166327-6417dc62-57a4-4c72-bbb6-6c6f77d0e189.mov

@ZlatanBajric what do you think about this solution? When in view -> show the post

**Comment by ZlatanBajric** [comment]
That is good enough, the question is performance. Example the loading screen before the page shows. That does not look good, and what happens when they have 200 posts? How will that affect the performance

**Comment by MelikaH-seeba** [comment]
https://user-images.githubusercontent.com/57252386/128170842-a6af4b59-0168-448a-9a37-0aa2d829e709.mov

@ZlatanBajric we are using dynamic loading with lazy load meaning the resources are loaded only when they are visible on the screen, so it should not effect the performance no matter how many posts there are.
