### ISSUE TITLE
Promo labels and discounted prices - Looks terrible 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#95]
<img width="306" alt="Skärmavbild 2021-07-29 kl  10 38 42" src="https://user-images.githubusercontent.com/48952732/127460353-72f4a381-8372-4505-8abd-4d13ca0e3cd8.png">

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done

**Comment by ZlatanBajric** [comment]
<img width="560" alt="Skärmavbild 2021-07-29 kl  13 02 06" src="https://user-images.githubusercontent.com/48952732/127481032-19186999-1d16-4ef0-8a3c-51e342652f46.png">
Can we do the same here?

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done
