### ISSUE TITLE
Missing translations 

### ISSUE THREAD

**Issue by ZlatanBajric** [seeba-se/Prep-Haven#99]
<img width="646" alt="Skärmavbild 2021-07-29 kl  13 02 29" src="https://user-images.githubusercontent.com/48952732/127481066-552852ff-8b9b-44c3-ad60-437ad9c4598e.png">

**Comment by MelikaH-seeba** [comment]
@ZlatanBajric done + added these custom fields for accordions/tabs titles. If they are empty **Beskrivning**
**Näringsinnehåll**
**Återbetalningspolicy**
**Fraktinformation**
will show on their places

<img width="953" alt="Screenshot 2021-07-29 at 14 06 45" src="https://user-images.githubusercontent.com/57252386/127488895-c23f6b38-cffb-4a34-bc4b-5a38bda18aba.png">
